# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: make install
    - name: Lint with pylint
      run: make lint
    - name: Test with Pytest
      run: make test
    - name: Run hello script
      run: make hello

 
